# action.yml
name: "gotest-to-html"
description: "automatically opens PR for upstream krew-index repo when you publish new release of your awesome plugin"
runs:
  using: "docker"
  image: "docker://rajatjindal/gotest-to-html:v0.0.1"
inputs:
  title-primary:
    description: "displayed in navigation with highlighted background"
  title-secondary:
    description: "displayed in navigation next to primary title"
  tags:
    description: "tags associated with this execution"
  format:
    description: "html or json"
